create type "public"."BreastSide" as enum ('left', 'right');

create table "public"."breastfeeding_segments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "baby_id" uuid not null,
    "feeding_id" bigint not null,
    "side" "BreastSide" not null,
    "start_at" timestamp with time zone not null,
    "end_at" timestamp with time zone not null
);


alter table "public"."breastfeeding_segments" enable row level security;

CREATE UNIQUE INDEX breastfeeding_segments_pkey ON public.breastfeeding_segments USING btree (id);

alter table "public"."breastfeeding_segments" add constraint "breastfeeding_segments_pkey" PRIMARY KEY using index "breastfeeding_segments_pkey";

alter table "public"."breastfeeding_segments" add constraint "breastfeeding_segments_baby_id_fkey" FOREIGN KEY (baby_id) REFERENCES babies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."breastfeeding_segments" validate constraint "breastfeeding_segments_baby_id_fkey";

alter table "public"."breastfeeding_segments" add constraint "breastfeeding_segments_feeding_id_fkey" FOREIGN KEY (feeding_id) REFERENCES feedings(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."breastfeeding_segments" validate constraint "breastfeeding_segments_feeding_id_fkey";

grant delete on table "public"."breastfeeding_segments" to "anon";

grant insert on table "public"."breastfeeding_segments" to "anon";

grant references on table "public"."breastfeeding_segments" to "anon";

grant select on table "public"."breastfeeding_segments" to "anon";

grant trigger on table "public"."breastfeeding_segments" to "anon";

grant truncate on table "public"."breastfeeding_segments" to "anon";

grant update on table "public"."breastfeeding_segments" to "anon";

grant delete on table "public"."breastfeeding_segments" to "authenticated";

grant insert on table "public"."breastfeeding_segments" to "authenticated";

grant references on table "public"."breastfeeding_segments" to "authenticated";

grant select on table "public"."breastfeeding_segments" to "authenticated";

grant trigger on table "public"."breastfeeding_segments" to "authenticated";

grant truncate on table "public"."breastfeeding_segments" to "authenticated";

grant update on table "public"."breastfeeding_segments" to "authenticated";

grant delete on table "public"."breastfeeding_segments" to "service_role";

grant insert on table "public"."breastfeeding_segments" to "service_role";

grant references on table "public"."breastfeeding_segments" to "service_role";

grant select on table "public"."breastfeeding_segments" to "service_role";

grant trigger on table "public"."breastfeeding_segments" to "service_role";

grant truncate on table "public"."breastfeeding_segments" to "service_role";

grant update on table "public"."breastfeeding_segments" to "service_role";


